# Travis example for Identifier created by Rafael Garibotti

sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - valgrind
      - cppcheck
      - gcovr
before-install:
  - sudo apt install cppcheck
  - sudo apt install valgrind
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - cd Crypt; make
  - cd Crypt; make cov
  - cd Crypt; make cppcheck
  - cd Crypt; make compile sanitizer
  - cd Crypt; make compile run
  - cd Crypt; make compile valgrind
